packages:
  - "examples/*"
  - "examples/*/*"
  - "examples/*/*/*"
  - "packages/*"
  - "integration-tests"
  - "integration-tests/test-api"
  - "integration-tests/test-apps/nextjs"
  - "integration-tests/test-apps/nuxt"
  - "integration-tests/test-apps/remix"
  - "integration-tests/test-apps/sveltekit"
  - "integration-tests/test-apps/solidstart"
  - "integration-tests/test-apps/standalone/dotenv-vercel"
