packages:
  - "examples/*"
  - "packages/*"
  - "integration-tests"
  - "integration-tests/test-apps/nextjs"
  - "integration-tests/test-apps/nuxt"
  - "integration-tests/test-apps/remix"
  - "integration-tests/test-apps/sveltekit"
  - "integration-tests/test-apps/solidstart"
