// Generated by nitro
import type { Serialize, Simplify } from "nitropack";
declare module "nitropack" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
  interface InternalApi {
    "/__nuxt_error": {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import("../../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@20.11.15_encoding@0.1.13_eslint@8.56.0_ioredis@_yabsd26omtz2cll5v6crw5s7ti/node_modules/nuxt/dist/core/runtime/nitro/renderer").default
            >
          >
        >
      >;
    };
  }
}
export {};
