name: Prepare Publish

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Prepare Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Setup pnpm & install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run changeset:consume
          commit: "meta(changelog): Update package versions"
          title: "meta(changelog): Update package versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
