name: Publish

on:
  push:
    branches:
      - main
    paths:
      - '**/CHANGELOG.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    # For whatever reason, yaml does not like the full "meta(changelog): Update package versions" string
    # So we check this in two parts
    if: |
      contains(github.event.head_commit.message, 'meta(changelog)') 
      && contains(github.event.head_commit.message, 'Update package versions')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Setup pnpm & install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Publish to NPM
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: pnpm changeset:publish
          createGithubReleases: true
