name: Test API Image CI

on:
  pull_request:
    paths:
      - integration-tests/test-api/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build:
    name: Build API Test
    uses: codecov/gha-workflows/.github/workflows/build-and-push-dockerhub.yml@v1.2.14
    secrets: inherit
    with:
        push: false
        image_name: codecov-javascript-bundler-plugins-test-api
        docker_path: integration-tests/test-api
