name: Test API Image Push

on:
  push:
    branches:
      - main
    paths:
      - integration-tests/test-api/**

permissions:
  content: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  push:
    name: Push API Test
    if: github.repository_owner == 'codecov'
    uses: codecov/gha-workflows/.github/workflows/build-and-push-dockerhub.yml@v1.2.14
    secrets: inherit
    with:
      push: true
      image_name: codecov-javascript-bundler-plugins-test-api
      docker_path: integration-tests/test-api
