name: Publish TypeDocs

on:
  workflow_dispatch:

jobs:
  deploy_docs:
    permissions:
      contents: 'write'
    name: Deploy TypeDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.RELEASER_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: Setup Git
        run: |
          echo "machine github.com login x password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          git config --global url."https://github.com/".insteadOf "git://github.com/"
          git config --global advice.detachedHead false
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Setup pnpm & install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Publish new docs
        run: node scripts/publish-docs.mjs